### Numpyで行列を表現しようとする時の良くある問題 Wes McKinney, chap12

In [11]:
import numpy as np
X =  np.array([[ 8.82768214,  3.82222409, -1.14276475,  2.04411587],
               [ 3.82222409,  6.75272284,  0.83909108,  2.08293758],
               [-1.14276475,  0.83909108,  5.01690521,  0.79573241],
               [ 2.04411587,  2.08293758,  0.79573241,  6.24095859]])
X[:, 0]  # これだと１次元で返ってしまう。
y = X[:, :1]  # two-dimensional by slicing
X

array([[ 8.82768214,  3.82222409, -1.14276475,  2.04411587],
       [ 3.82222409,  6.75272284,  0.83909108,  2.08293758],
       [-1.14276475,  0.83909108,  5.01690521,  0.79573241],
       [ 2.04411587,  2.08293758,  0.79573241,  6.24095859]])

In [12]:
y

array([[ 8.82768214],
       [ 3.82222409],
       [-1.14276475],
       [ 2.04411587]])

In [8]:
np.dot(y.T, np.dot(X, y))

array([[ 1195.46796121]])

Numpyには一応Matrixクラスが用意されている。具体的なご利益は一つの行を抜き出しても２次元を保つ。＊による乗算が行列演算の意味になる。

In [13]:
Xm = np.matrix(X)
ym = Xm[:, 0]

In [14]:
Xm

matrix([[ 8.82768214,  3.82222409, -1.14276475,  2.04411587],
        [ 3.82222409,  6.75272284,  0.83909108,  2.08293758],
        [-1.14276475,  0.83909108,  5.01690521,  0.79573241],
        [ 2.04411587,  2.08293758,  0.79573241,  6.24095859]])

In [15]:
ym

matrix([[ 8.82768214],
        [ 3.82222409],
        [-1.14276475],
        [ 2.04411587]])

In [16]:
ym.T * Xm * ym

matrix([[ 1195.46796121]])

In [17]:
Xm.I * X

matrix([[  1.00000000e+00,  -2.08166817e-17,  -5.55111512e-17,
           5.55111512e-17],
        [  1.52655666e-16,   1.00000000e+00,   5.55111512e-17,
           5.55111512e-17],
        [  1.11022302e-16,   2.77555756e-17,   1.00000000e+00,
           1.38777878e-17],
        [ -5.55111512e-17,   0.00000000e+00,   3.46944695e-18,
           1.00000000e+00]])

でも全てにNumpy.matrixを使うのはあまりオススメしない。行列演算部分が終わったら、asarray()でキャストし直すと良い。