### 12.2.1 配列の再形成 Reshaping arrays

In [18]:
import numpy as np
arr = np.arange(8)
arr
arr.reshape((4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

多次元配列でも再形成可能。

In [19]:
arr.reshape((4, 2)).reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

次元の一つに-1を渡すとその次元の要素数はデータから推測される。

In [20]:
arr = np.arange(15)
arr.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

shape属性から取り出したタプルを、そのままreshapeに渡す。

In [21]:
other_arr = np.ones((3, 5))
other_arr.shape

(3, 5)

In [22]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

これまでは１次元から低次元の変換だった。平坦化や解きほぐしはその逆。

In [25]:
arr = np.arange(15).reshape((5, 3))
arr
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

ravelは必要なければコピーを作らないがflattenは常にコピーを作る。